src/main/java/com/investmetic/global/util/s3/FilePath.java, src/main/java/com/investmetic/global/util/s3/S3FileService.java, src/test/java/com/investmetic/global/util/s3/S3FileServiceTest.java
1. application.yml 에서 s3 PresignedUrl expiration 가져올 수 있도록 수정.(naming은 좀 봐주세요...)
2. 파일명에 UUID 8글자 추가. ex.)9b1deb4dtestimage.jpa
3. 문의하기 파일 경로 제거, 공지사항 로직 추가.
4. 확장명 유효성 검사시 HashSet사용.
=> :recycle: [refactor] S3FileService 리팩토링 및 TestCode 추가

src/main/java/com/investmetic/domain/review/dto/response/ReviewDetailResponse.java, src/test/java/com/investmetic/domain/TestEntity/TestEntityFactory.java
- 리뷰 오류 수정 
> ex) #59 
- 리뷰 생성자 오류 해결 
-  테스트코드 오류 해결
=> Refactor review #59

build.gradle, src/test/java/com/investmetic/domain/review/service/ReviewServiceTest.java
- 테스트db삭제
- 리뷰 테스트코드 문제해결
> ex) 
- 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
- 테스트용 db삭제
=> 🐛 [fix] 리뷰 테스트코드 문제해결

src/main/java/com/investmetic/domain/accountverification/service/AccountVerificationService.java, src/main/java/com/investmetic/domain/notice/model/entity/Notice.java, src/main/java/com/investmetic/domain/qna/model/entity/Answer.java, src/main/java/com/investmetic/domain/strategy/controller/TradeTypeController.java, src/main/java/com/investmetic/domain/strategy/model/entity/StockType.java, src/main/java/com/investmetic/domain/strategy/repository/DailyAnalysisRepositoryCustomImpl.java, src/main/java/com/investmetic/domain/strategy/repository/StrategyRepositoryCustomImpl.java, src/main/java/com/investmetic/domain/user/controller/EmailAuthController.java, src/main/java/com/investmetic/domain/user/model/entity/User.java, src/main/java/com/investmetic/domain/user/service/EmailService.java, src/main/java/com/investmetic/global/exception/ErrorCode.java, src/main/java/com/investmetic/global/util/s3/S3FileService.java, src/test/java/com/investmetic/domain/strategy/service/StockTypeServiceTest.java, src/test/java/com/investmetic/domain/strategy/service/StrategyDetailServiceTest.java, src/test/java/com/investmetic/domain/user/repository/UserMyPageRepositoryTest.java, src/test/java/com/investmetic/domain/user/service/UserMyPageServiceTest.java, src/test/java/com/investmetic/domain/user/service/UserServiceTest.java, src/test/java/com/investmetic/global/util/s3/S3FileServiceTest.java
- 실계좌 인증 등록 로직 수정 및 일부 리팩토링
> #76 
- S3 파일 서비스 UUID가 추가됨에 따라 실계좌 인증 등록 로직 수정
- 예외처리 일부 수정
=> Feature/refactor account verification #76

src/main/java/com/investmetic/domain/strategy/controller/StrategyController.java, src/main/java/com/investmetic/domain/strategy/model/entity/Strategy.java, src/main/java/com/investmetic/domain/strategy/service/StrategyService.java, src/test/java/com/investmetic/domain/strategy/service/StrategyServiceTest.java
- 전략 공개 여부 수정 기능
> ex) #이슈번호, #이슈번호
- 전략 공개 여부 수정
- 테스트 코드 작성
=> Feat/update strategy visibility #38

src/main/java/com/investmetic/domain/accountverification/controller/AccountVerificationController.java, src/main/java/com/investmetic/domain/strategy/controller/StrategyController.java, src/main/java/com/investmetic/domain/strategy/service/StrategyService.java, src/test/java/com/investmetic/domain/strategy/service/StrategyServiceTest.java
- 트레이더 전략 삭제 기능
> #30 
- 트레이더 전략 삭제 기능
- 트레이더 전략 삭제 테스트 코드
=> Feat/trader delete strategy #30

src/main/java/com/investmetic/domain/user/controller/EmailAuthController.java
- 이메일 인증 및 확인 기능 엔드포인트 url 변경
> #111
1. emailAddr에서 email로 수정
2. "/api/users/authenticate"로 Post, Get맵핑(EmailAuthController)
Test코드 최대한 안건들이기 위해
userService.verifyEmailCode(requestDto.getEmail(), requestDto.getCode()); 로 진행하였습니다.
=> :bug: [Fix] :  이메일 인증 및 확인 엔드포인트 및 변수명 수정

src/main/java/com/investmetic/InvestMeticApplication.java, src/main/java/com/investmetic/domain/accountverification/dto/response/AccountImagesResponseDto.java, src/main/java/com/investmetic/domain/accountverification/repository/AccountVerificationRepository.java, src/main/java/com/investmetic/domain/accountverification/service/AccountVerificationService.java, src/main/java/com/investmetic/domain/strategy/controller/StrategyDetailController.java, src/main/java/com/investmetic/domain/strategy/service/StrategyDetailService.java, src/main/java/com/investmetic/global/config/QuerydslConfig.java, src/test/java/com/investmetic/domain/accountverification/service/AccountVerificationServiceTest.java
- 실계좌 이미지 목록조회 기능구현 (전략 상세페이지)
> ex) #37 
- 실계좌 이미지 목록조회 기능구현 (전략 상세페이지)
- 페이징 10개
- 최신순 정렬
- 병훈님꺼 서비스코드랑 dto 그대로 쓴거라 테스트 코드 작성 X
=> Feat/strategiy account verification #37

src/main/java/com/investmetic/domain/user/controller/UserController.java, src/main/java/com/investmetic/domain/user/dto/object/ImageMetadata.java, src/main/java/com/investmetic/domain/user/dto/object/TraderListSort.java, src/main/java/com/investmetic/domain/user/dto/response/TraderProfileDto.java, src/main/java/com/investmetic/domain/user/repository/UserRepositoryCustom.java, src/main/java/com/investmetic/domain/user/repository/UserRepositoryCustomImpl.java, src/main/java/com/investmetic/domain/user/service/UserService.java, src/test/java/com/investmetic/domain/user/controller/UserMyPageControllerTest.java, src/test/java/com/investmetic/domain/user/repository/TraderListRepositoryTest.java, src/test/java/com/investmetic/domain/user/repository/UserMyPageRepositoryTest.java, src/test/java/com/investmetic/domain/user/service/TraderListTest.java, src/test/java/com/investmetic/domain/user/service/UserInfoModifyServiceTest.java, src/test/java/com/investmetic/domain/user/service/UserServiceTest.java
> 트레이더 목록 조회시 enum
> 회원 수정 및 회원 가입시 imageData Extesion받아오지 않게 했습니다.
> ## #️⃣연관된 이슈
> #125
- 스웨거, 빌드 테스트 모두 했습니다.
- [ ㅇ] PR 이전 `dev` 브랜치 병합 하셨나요?
- [ㅇ ] PR 이전 빌드 테스트 정상적으로 성공했나요?
- [ㅇ ] PR 상세내용이 충분히 기재 되었나요?
- [ ㅇ] PR 리뷰어, 할당자, 라벨, 프로젝트 확인
=> Fix/user trader #125

src/main/java/com/investmetic/domain/user/controller/EmailAuthController.java, src/main/java/com/investmetic/domain/user/controller/UserAdminController.java, src/main/java/com/investmetic/domain/user/controller/UserController.java, src/main/java/com/investmetic/domain/user/controller/UserMyPageController.java, src/main/java/com/investmetic/domain/user/dto/request/UserSignUpDto.java, src/main/java/com/investmetic/domain/user/service/UserService.java, src/main/java/com/investmetic/global/util/RedisUtil.java, src/test/java/com/investmetic/domain/user/service/EmailServiceTest.java, src/test/java/com/investmetic/domain/user/service/UserServiceTest.java
> 회원가입시 email 인증 코드 추가하여 받도록 하였습니다.
> ## #️⃣연관된 이슈
>  #127 
- 인증코드 입력시 30분이 지나면 nullPointException발생 가능하여 Optional로 변경하여 처리하였습니다.
(RedisUtil.getData( ) -> Optional)
- 회원 가입 인증코드 검증 api에서 인증코드를 redis로부터 삭제하지않고 회원가입 api에서 인증코드를 redis로부터 삭제하도록 하였습니다. 
- Swagger 문서 한글 설명 추가하였습니다.
- postman 확인 하였습니다.
- [o] PR 이전 `dev` 브랜치 병합 하셨나요?
- [o] PR 이전 빌드 테스트 정상적으로 성공했나요?
- [o] PR 상세내용이 충분히 기재 되었나요?
- [o] PR 리뷰어, 할당자, 라벨, 프로젝트 확인
=> Feat/signup email #127

src/test/java/com/investmetic/domain/user/repository/TraderListRepositoryTest.java
> 트레이더 목록 테스트코드 오류 수정
> ## #️⃣연관된 이슈
> #140 
-
=> 🐛 [fix] 트레이더 목록 테스트코드 오류 수정

src/main/java/com/investmetic/domain/strategy/model/entity/MonthlyAnalysis.java, src/main/java/com/investmetic/domain/strategy/model/entity/Strategy.java, src/main/java/com/investmetic/domain/strategy/repository/DailyAnalysisRepository.java, src/main/java/com/investmetic/domain/strategy/repository/MonthlyAnalysisRepository.java, src/main/java/com/investmetic/global/scheduler/DailyAnalysisScheduler.java, src/main/java/com/investmetic/global/scheduler/MonthlyAnalysisScheduler.java, src/main/java/com/investmetic/global/scheduler/Scheduler.java, src/main/java/com/investmetic/global/scheduler/StrategySmScoreScheduler.java, src/test/java/com/investmetic/domain/strategy/service/StrategyDailyAnalysisServiceTest.java
> kp ratio, sm score 계산식 수정 및 월간 분석 추가
> ## #️⃣연관된 이슈
> #138
-
=> ♻️ [refactor] kp ratio, sm score 계산식 수정 및 월간 분석 추가

src/main/java/com/investmetic/domain/user/controller/UserController.java, src/main/java/com/investmetic/domain/user/dto/request/LoginRequestDto.java, src/main/java/com/investmetic/domain/user/dto/response/CustomUserDetails.java, src/main/java/com/investmetic/domain/user/service/LogoutService.java, src/main/java/com/investmetic/domain/user/service/UserDetailService.java, src/main/java/com/investmetic/global/config/AuditConfig.java, src/main/java/com/investmetic/global/config/SecurityConfig.java, src/main/java/com/investmetic/global/exception/ErrorCode.java, src/main/java/com/investmetic/global/exception/GlobalExceptionHandler.java, src/main/java/com/investmetic/global/security/CustomUserDetails.java, src/main/java/com/investmetic/global/security/filter/JWTFilter.java, src/main/java/com/investmetic/global/security/filter/LoginFilter.java, src/main/java/com/investmetic/global/security/handler/CustomAuthenticationSuccessHandler.java, src/main/java/com/investmetic/global/security/service/CustomUserDetailService.java, src/main/java/com/investmetic/global/security/service/ReIssueService.java, src/main/java/com/investmetic/global/util/JWTUtil.java
> Security 기능 리팩토링
> ## #️⃣연관된 이슈
> #136 
- access_token -> access-token 로 키값 변경
- AuditConfig 추가
- username-> email로 변경
- loginSuccessHandler에서
String email = authentication.getName(); 메서드를 호출하면 
AbstractAuthenticationToken로인해 CustomUserDetails의 getUsername이 호출됩니다.
따라서 일단 getUsername을 하게되면 email을 반환하도록 하였습니다.
=> Refactor/spring security 기능 리팩토링 #136

src/main/java/com/investmetic/global/scheduler/DailyAnalysisScheduler.java, src/main/java/com/investmetic/global/scheduler/Scheduler.java, src/main/java/com/investmetic/global/scheduler/StrategyCalculatorScheduler.java
> kp ratio 계산식 문제 수정
> ## #️⃣연관된 이슈
> #145 
-
=> 🐛 [fix] kp ratio 계산식 수정

src/main/java/com/investmetic/domain/user/dto/request/UserSignUpDto.java, src/main/java/com/investmetic/global/config/SecurityConfig.java
> 다른 origin일 경우 Access-Control-Request-Headers 에 access-token 가능하게 추가 하였습니다.
또한 회원가입시 일단 핸드폰 번호 유효성 검사 삭제하였습니다.
> ## #️⃣연관된 이슈
> ex) #148 
- 몇줄 추가 안했습니다.
- postman에서 확인은 했어요.
=> :bug: [bugHot] : security custom header 추가

src/main/java/com/investmetic/domain/strategy/controller/StrategyController.java, src/main/java/com/investmetic/domain/strategy/service/StrategyAnalysisService.java, src/main/java/com/investmetic/domain/user/model/entity/User.java, src/main/java/com/investmetic/global/config/SwaggerConfig.java, src/test/java/com/investmetic/domain/strategy/service/StrategyDailyAnalysisServiceTest.java
> 전략 일간 분석 추가 기능 권한 로직 추가 및 스웨거 액세스토큰 부분 수정
> ## #️⃣연관된 이슈
> #143 
- 스웨거 액세스토큰 쪽도 수정했습니다.
=> Refactor/trader create daily analysis #143

src/main/java/com/investmetic/domain/review/controller/ReviewController.java, src/main/java/com/investmetic/domain/strategy/controller/StrategyController.java, src/main/java/com/investmetic/domain/strategy/controller/StrategyDetailController.java, src/main/java/com/investmetic/domain/strategy/controller/StrategyRankingController.java, src/main/java/com/investmetic/domain/strategy/service/StrategyAnalysisService.java, src/main/java/com/investmetic/domain/user/model/entity/User.java, src/test/java/com/investmetic/domain/strategy/service/StrategyDailyAnalysisServiceTest.java
- 전략 일간 분석 수정 권한 추가
- 기존 일간 분석 데이터 존재 유무에 따른 로직 추가
- 전략 일간 분석 등록 시 기존 일간 분석 데이터가 존재할 경우에 대한 예외 처리 추가
- 전략 일간 분석 등록 및 수정 테스트코드 수정
> ## #️⃣연관된 이슈
> #151
-
=> Refactor/trader modify daily analysis #151

src/main/java/com/investmetic/domain/strategy/controller/StrategyController.java, src/main/java/com/investmetic/domain/strategy/model/entity/DailyAnalysis.java, src/main/java/com/investmetic/domain/strategy/model/entity/Strategy.java, src/main/java/com/investmetic/domain/strategy/repository/TradeTypeRepository.java, src/main/java/com/investmetic/domain/strategy/service/StrategyService.java, src/main/java/com/investmetic/global/scheduler/DailyAnalysisScheduler.java, src/test/java/com/investmetic/domain/strategy/service/StrategyServiceTest.java
- 전략 등록 권한 확인 로직 수정
- 전략 등록 테스트 코드 추가
- 전략 수정 페이지 진입 시 해당 전략 정보 조회 권한 확인 로직 추가
- 전략 수정 페이지 진입 시 해당 전략 정보 조회 테스트 코드 추가
- 전략 수정 권한 확인 로직 추가
- 전략 권한 제안서 변경 유무에 따른 로직 수정
- 전략 수정 권한 테스트 코드 추가
- 전략 공개 여부 수정 기능 권한 확인 로직 추가
- 전략 공개 여부 수정 테스트 코드 추가
- 전략 삭제 로직 수정
- 전략 삭제 권한 확인 로직 추가
- 전략 삭제 테스트 코드 추가
> ## #️⃣연관된 이슈
> #153 
- 전략 부분 모두 권한 추가 및 예외처리에 대한 로직 전부 수정하였습니다.
=> Refactor/strategy authorization #153

src/main/java/com/investmetic/global/security/handler/CustomAuthenticationSuccessHandler.java
> 추가하려는 기능에 대해 간결하게 설명해주세요
> ## #️⃣연관된 이슈
> ex) #이슈번호, #이슈번호
-
=> 🐛  [refactor] cookie "/" 추가

src/main/java/com/investmetic/global/config/CorsProperties.java, src/main/java/com/investmetic/global/config/SecurityConfig.java
> cors 문제 해결
> ## #️⃣연관된 이슈
> #162 
- cors 문제 해결
=> 🐛 [fix] cors 문제 해결

src/main/java/com/investmetic/domain/accountverification/repository/AccountVerificationRepository.java, src/main/java/com/investmetic/domain/review/repository/ReviewRepository.java, src/main/java/com/investmetic/domain/strategy/repository/MonthlyAnalysisRepository.java, src/main/java/com/investmetic/domain/strategy/repository/StockTypeGroupRepository.java, src/main/java/com/investmetic/domain/strategy/service/StrategyService.java, src/main/java/com/investmetic/domain/subscription/repository/SubscriptionRepositoryCustom.java, src/main/java/com/investmetic/domain/subscription/repository/SubscriptionRepositoryCustomImpl.java, src/main/java/com/investmetic/global/exception/ErrorCode.java, src/main/java/com/investmetic/global/util/s3/FilePath.java, src/main/java/com/investmetic/global/util/s3/S3FileService.java, src/test/java/com/investmetic/domain/strategy/service/StrategyServiceTest.java
> 전략 삭제 시 관련된 전략 부분 전체 삭제 로직 추가
> ## #️⃣연관된 이슈
> #156 
- 살려주세요
=> 🐛 [fix] 전략 삭제 시 관련된 전략 부분 전체 삭제 로직 추가

src/main/java/com/investmetic/domain/review/dto/response/ReviewDetailResponse.java, src/main/java/com/investmetic/domain/review/dto/response/ReviewResponse.java, src/main/java/com/investmetic/domain/subscription/controller/SubscribeController.java, src/main/java/com/investmetic/domain/subscription/service/SubscriptionService.java, src/main/java/com/investmetic/global/exception/ErrorCode.java, src/test/java/com/investmetic/domain/subscription/service/SubscribtionServiceTest.java
> 리뷰 및 전략 조회 버그 해결 및 리팩토링
> ## #️⃣연관된 이슈
> ex) #163
=> 리뷰목록조회 버그 해결 및 구독 리팩토링

src/main/java/com/investmetic/domain/strategy/repository/DailyAnalysisRepositoryCustomImpl.java
> 전략 분석그래프 데이터 오류 수정
> ## #️⃣연관된 이슈
> ex) #174 
-
=> 🐛 [fix] 전략 분석그래프 데이터 오류 수정

src/main/java/com/investmetic/domain/strategy/controller/StrategyController.java, src/main/java/com/investmetic/domain/strategy/dto/request/StrategyModifyRequestDto.java, src/main/java/com/investmetic/domain/strategy/dto/request/StrategyRegisterRequestDto.java, src/main/java/com/investmetic/domain/strategy/dto/request/TraderDailyAnalysisRequestDto.java, src/main/java/com/investmetic/domain/strategy/service/StrategyAnalysisService.java, src/main/java/com/investmetic/global/exception/BaseResponse.java, src/main/java/com/investmetic/global/exception/ErrorCode.java, src/main/java/com/investmetic/global/exception/GlobalExceptionHandler.java, src/test/java/com/investmetic/domain/user/controller/UserAdminPageControllerTest.java, src/test/java/com/investmetic/domain/user/controller/UserMyPageControllerTest.java
- 전략 유효성 검사 추가
- 전역예외처리 수정(유효성 검사 부분)
> ## #️⃣연관된 이슈
> #172
-
=> 🐛 [fix] 전략 관련 유효성 검사 추가

src/main/java/com/investmetic/domain/user/controller/UserController.java, src/main/java/com/investmetic/domain/user/dto/response/AvaliableDto.java, src/main/java/com/investmetic/domain/user/service/UserService.java, src/test/java/com/investmetic/domain/user/service/UserServiceTest.java
> 이메일,닉네임,전화번호 중복체크 시에 null 체크 및 조건에 맞는 값인지 검증
> ## #️⃣연관된 이슈 
> #167 
- 이메일, 닉네임, 전화번호 null 값인 경우, 응답 dto에 "isAvailable": false 로 응답하게 수정헸습니다.
=> Fix/닉네임 중복체크 조건 추가 #167

src/main/java/com/investmetic/domain/accountverification/controller/AccountVerificationController.java, src/main/java/com/investmetic/domain/accountverification/service/AccountVerificationService.java, src/main/java/com/investmetic/domain/strategy/service/StrategyService.java, src/main/java/com/investmetic/global/util/s3/FilePath.java, src/main/java/com/investmetic/global/util/s3/S3FileService.java, src/test/java/com/investmetic/domain/accountverification/service/AccountVerificationServiceTest.java, src/test/java/com/investmetic/domain/strategy/service/StrategyServiceTest.java
> 전략 아이디마다 s3폴더 만들기
> ## #️⃣연관된 이슈
> #160
- 고치고 싶으신거 있으면 고쳐주세요. 사랑합니다.
=> Refactor/s3 strategy folder #160

src/main/java/com/investmetic/domain/qna/controller/AnswerController.java, src/main/java/com/investmetic/domain/qna/controller/QuestionController.java, src/main/java/com/investmetic/domain/qna/dto/request/AnswerRequestDto.java, src/main/java/com/investmetic/domain/qna/dto/request/QuestionRequestDto.java, src/main/java/com/investmetic/domain/qna/model/entity/Question.java, src/main/java/com/investmetic/domain/qna/service/AnswerService.java, src/main/java/com/investmetic/domain/qna/service/QuestionService.java, src/test/java/com/investmetic/domain/qna/service/QuestionServiceTest.java, src/test/java/com/investmetic/domain/strategy/service/AdminStrategyServiceTest.java, src/test/java/com/investmetic/domain/strategy/service/StockTypeServiceTest.java, src/test/java/com/investmetic/domain/strategy/service/TradeTypeServiceTest.java
> 문의 관련 문제 사항 전체 수정
> ## #️⃣연관된 이슈
> #179
- 목록 조회 경우 POST -> GET 메서드로 변경하였습니다.
=> Fix/question #179

src/main/java/com/investmetic/domain/qna/service/QuestionService.java
> 트레이더 문의 목록 조회 내용이 반환 되지 않는 문제 수정
> ## #️⃣연관된 이슈
> #188 
-
=> 🐛 [fix] 트레이더 문의 목록 조회 내용이 반환 되지 않는 문제 수정

src/main/java/com/investmetic/domain/qna/dto/request/QuestionRequestDto.java
> 투자자 문의 등록 시에 필요한 DTO 수정
> ## #️⃣연관된 이슈
> #190 
-
=> 🐛 [fix] 투자자 문의 등록 시에 필요한 DTO 수정

src/main/java/com/investmetic/domain/qna/controller/AnswerController.java, src/main/java/com/investmetic/domain/qna/dto/request/AnswerRequestDto.java, src/main/java/com/investmetic/domain/qna/dto/response/AnswerResponseDto.java, src/main/java/com/investmetic/domain/qna/dto/response/QuestionsResponse.java, src/main/java/com/investmetic/domain/qna/model/entity/Answer.java, src/main/java/com/investmetic/domain/qna/service/AnswerService.java, src/main/java/com/investmetic/domain/qna/service/QuestionService.java
> 문의 상세 조회 시 답변자 정보 데이터 조회 추가
> ## #️⃣연관된 이슈
> #196 
-
=> 🐛 [fix] 문의 상세 조회 시 답변자 정보 데이터 조회 추가

src/main/java/com/investmetic/domain/strategy/controller/StrategyController.java, src/main/java/com/investmetic/domain/strategy/model/entity/DailyAnalysis.java, src/main/java/com/investmetic/domain/strategy/repository/DailyAnalysisRepository.java, src/main/java/com/investmetic/domain/strategy/service/StrategyAnalysisService.java, src/main/java/com/investmetic/domain/strategy/service/StrategyService.java
> 전략 권한 로직 추가 및 일간 분석 일부 삭제 로직 변경
> ## #️⃣연관된 이슈
> #185 
-
=> 🐛 [fix] 전략 권한 로직 추가 및 일간 분석 일부 삭제 로직 변경

src/test/java/com/investmetic/domain/strategy/service/FileDownloadServiceTest.java, src/test/java/com/investmetic/domain/strategy/service/StrategyDailyAnalysisServiceTest.java
> 전략 제안서 및 일간분석 삭제 테스트 코드 오류 수정
> ## #️⃣연관된 이슈
> #199 
-
=> 🐛 [fix] 전략 제안서 및 일간분석 삭제 테스트 코드 오류 수정

src/main/java/com/investmetic/domain/qna/service/QuestionService.java
> 답변 대기 중일 경우 null로 인해 조회가 안되는 문제 해결
> ## #️⃣연관된 이슈
> #201 
-
=> 🐛 [fix] 답변 대기 중일 경우 null로 인해 조회가 안되는 문제 해결

src/main/java/com/investmetic/domain/accountverification/controller/AccountVerificationController.java, src/main/java/com/investmetic/domain/qna/service/QuestionService.java
- 문의 상세 조 시 500 오류 문제 수정
- 실계좌 인증 조회 페이지 당 조회 갯수 수정
> ## #️⃣연관된 이슈
> #203
-
=> Fix/qna #203

src/main/java/com/investmetic/domain/user/controller/UserController.java, src/main/java/com/investmetic/domain/user/service/UserMyPageService.java, src/main/java/com/investmetic/domain/user/service/UserService.java, src/main/java/com/investmetic/global/exception/ErrorCode.java, src/main/java/com/investmetic/global/util/stibee/StibeeEmailService.java, src/main/java/com/investmetic/global/util/stibee/client/AutoApiStibeeClient.java, src/test/java/com/investmetic/domain/user/service/UserServiceTest.java
> 비밀번호 재설정 기능 추가
> ## #️⃣연관된 이슈
>  #11
1. 이메일에 인증코드 전송
2. 인증코드 검증
3. 비밀번호 재설정
유저 관련 모두 @Valid 설정 필요합니다.  유저 관련해서 브랜치 파서 전부 설정하겠습니다.
=> Feat/비밀번호 재설정 기능 구현 #11

src/main/java/com/investmetic/domain/user/controller/LoginController.java, src/main/java/com/investmetic/domain/user/controller/LogoutController.java, src/main/java/com/investmetic/domain/user/controller/ReIssueController.java, src/main/java/com/investmetic/domain/user/controller/UserController.java
> UserController Swagger 추가 및 수정
> ## #️⃣연관된 이슈
> 
UserController Swagger 추가 및 수정
-
=> ♻️ [refactor] UserController Swagger 추가 및 수정

src/main/java/com/investmetic/domain/accountverification/controller/AccountVerificationController.java, src/main/java/com/investmetic/domain/accountverification/service/AccountVerificationService.java, src/main/java/com/investmetic/domain/qna/controller/QuestionController.java, src/test/java/com/investmetic/domain/accountverification/service/AccountVerificationServiceTest.java
> 실계좌 인증 권한 로직 추가
> ## #️⃣연관된 이슈
> #208 
-
=> 🐛 [fix] 실계좌 인증 권한 로직 추가

src/main/java/com/investmetic/domain/qna/controller/AnswerController.java, src/main/java/com/investmetic/domain/qna/dto/response/QuestionsDetailResponse.java, src/main/java/com/investmetic/domain/qna/service/QuestionService.java
> QNA 오류 및 상세 조회 시 전략 ID 추가
> ## #️⃣연관된 이슈
> #203 
-
=> 🐛 [fix] QNA 오류 및 상세 조회 시 전략 ID 추가

src/main/java/com/investmetic/domain/strategy/model/entity/StrategyStatistics.java, src/main/java/com/investmetic/global/scheduler/StrategyStatisticsScheduler.java
> 통계계산 누락된값 수정
> ## #️⃣연관된 이슈
> ex) #214
-
=> 🐛 [fix] 통계계산 누락된값 수정

src/main/java/com/investmetic/domain/qna/dto/BaseQnAInfoDto.java, src/main/java/com/investmetic/domain/qna/dto/response/QuestionsResponse.java, src/main/java/com/investmetic/domain/qna/service/QuestionService.java
> 문의 조회(투자자, 트레이더, 관리자) DTO 수정
> ## #️⃣연관된 이슈
> #216 
- 살려주세요
=> 🐛 [fix] 문의 조회(투자자, 트레이더, 관리자) DTO 수정

src/main/java/com/investmetic/domain/strategy/controller/StrategyRankingController.java, src/main/java/com/investmetic/domain/strategy/repository/StrategyRepositoryCustom.java, src/main/java/com/investmetic/domain/strategy/repository/StrategyRepositoryCustomImpl.java, src/main/java/com/investmetic/domain/strategy/service/StrategyListingService.java
> 트레이더 전략 목록 조회 기능
> ## #️⃣연관된 이슈
> #219
- 트레이더 전략 목록 조회 기능
최대한 정훈님 코드파악후에 작성하였습니다. 확인 부탁드립니다.
=> :sparkles: [feat] : 트레이더 전략 목록 조회 기능

src/main/java/com/investmetic/domain/strategy/dto/response/statistic/AssetManagementDto.java, src/main/java/com/investmetic/domain/strategy/dto/response/statistic/DdMddInfoDto.java, src/main/java/com/investmetic/domain/strategy/dto/response/statistic/ProfitLossDto.java, src/main/java/com/investmetic/domain/strategy/dto/response/statistic/TradingInfoDto.java, src/main/java/com/investmetic/global/scheduler/DailyAnalysisScheduler.java, src/main/java/com/investmetic/global/scheduler/StrategyStatisticsScheduler.java
> 통계 응답 수정
> ## #️⃣연관된 이슈
> ex) #이슈번호, #이슈번호
- 통계 응답 수정
=> 🐛 [fix] 통계 응답 수정

src/main/java/com/investmetic/domain/qna/dto/QuestionStrategyInfoDto.java, src/main/java/com/investmetic/domain/qna/dto/response/QuestionsResponse.java, src/main/java/com/investmetic/domain/qna/service/QuestionService.java
> 관리자의 문의 조회시 전략명 반환값 수정
> ## #️⃣연관된 이슈
> #223
-
=> 🐛 [fix] 관리자의 문의 조회시 전략명 반환값 수정

src/main/java/com/investmetic/domain/strategy/dto/response/DailyAnalysisResponse.java, src/main/java/com/investmetic/domain/strategy/dto/response/MonthlyAnalysisResponse.java
> ♻️ [refactor] 일간분석, 월간분석 응답 소수점 수정
> ## #️⃣연관된 이슈
> ex) #226 
-
=> ♻️ [refactor] 일간분석, 월간분석 응답 소수점 수정

src/main/java/com/investmetic/domain/qna/controller/QuestionController.java, src/main/java/com/investmetic/domain/qna/service/QuestionService.java
> 문의 관리자 삭제 기능 추가
> ## #️⃣연관된 이슈
> ex) feat/question-answer-#47
-
=> ✨[feat] 문의사항 관리자 삭제 기능 추가
